const models = [
  {
    name: 'hiragana',
    label: [
      { romName: 'a', japName: 'あ' },
      { romName: 'i', japName: 'い' },
      { romName: 'u', japName: 'う' },
      { romName: 'e', japName: 'え' },
      { romName: 'o', japName: 'お' },
      { romName: 'ka', japName: 'か' },
      { romName: 'ga', japName: 'が' },
      { romName: 'ki', japName: 'き' },
      { romName: 'gi', japName: 'ぎ' },
      { romName: 'ku', japName: 'く' },
      { romName: 'gu', japName: 'ぐ' },
      { romName: 'ke', japName: 'け' },
      { romName: 'ge', japName: 'げ' },
      { romName: 'ko', japName: 'こ' },
      { romName: 'go', japName: 'ご' },
      { romName: 'sa', japName: 'さ' },
      { romName: 'za', japName: 'ざ' },
      { romName: 'shi', japName: 'し' },
      { romName: 'ji', japName: 'じ' },
      { romName: 'su', japName: 'す' },
      { romName: 'zu', japName: 'ず' },
      { romName: 'se', japName: 'せ' },
      { romName: 'ze', japName: 'ぜ' },
      { romName: 'so', japName: 'そ' },
      { romName: 'zo', japName: 'ぞ' },
      { romName: 'ta', japName: 'た' },
      { romName: 'da', japName: 'だ' },
      { romName: 'chi', japName: 'ち' },
      { romName: 'ji, dji', japName: 'ぢ' },
      { romName: 'tsu', japName: 'つ' },
      { romName: 'dzu', japName: 'づ' },
      { romName: 'te', japName: 'て' },
      { romName: 'de', japName: 'で' },
      { romName: 'to', japName: 'と' },
      { romName: 'do', japName: 'ど' },
      { romName: 'na', japName: 'な' },
      { romName: 'ni', japName: 'に' },
      { romName: 'nu', japName: 'ぬ' },
      { romName: 'ne', japName: 'ね' },
      { romName: 'no', japName: 'の' },
      { romName: 'ha', japName: 'は' },
      { romName: 'ba', japName: 'ば' },
      { romName: 'pa', japName: 'ぱ' },
      { romName: 'hi', japName: 'ひ' },
      { romName: 'bi', japName: 'び' },
      { romName: 'pi', japName: 'ぴ' },
      { romName: 'fu', japName: 'ふ' },
      { romName: 'bu', japName: 'ぶ' },
      { romName: 'pu', japName: 'ぷ' },
      { romName: 'he', japName: 'へ' },
      { romName: 'be', japName: 'べ' },
      { romName: 'pe', japName: 'ぺ' },
      { romName: 'ho', japName: 'ほ' },
      { romName: 'bo', japName: 'ぼ' },
      { romName: 'po', japName: 'ぽ' },
      { romName: 'ma', japName: 'ま' },
      { romName: 'mi', japName: 'み' },
      { romName: 'mu', japName: 'む' },
      { romName: 'me', japName: 'め' },
      { romName: 'mo', japName: 'も' },
      { romName: 'ya', japName: 'や' },
      { romName: 'yu', japName: 'ゆ' },
      { romName: 'yo', japName: 'よ' },
      { romName: 'ra', japName: 'ら' },
      { romName: 'ri', japName: 'り' },
      { romName: 'ru', japName: 'る' },
      { romName: 're', japName: 'れ' },
      { romName: 'ro', japName: 'ろ' },
      { romName: 'wa', japName: 'わ' },
      { romName: 'wo', japName: 'を' },
      { romName: 'n', japName: 'ん' },
    ],
  },
  {
    name: 'katakana',
    label: [
      { romName: 'a', japName: 'ア' },
      { romName: 'i', japName: 'イ' },
      { romName: 'u', japName: 'ウ' },
      { romName: 'e', japName: 'エ' },
      { romName: 'o', japName: 'オ' },
      { romName: 'ka', japName: 'カ' },
      { romName: 'ki', japName: 'キ' },
      { romName: 'ku', japName: 'ク' },
      { romName: 'ke', japName: 'ケ' },
      { romName: 'ko', japName: 'コ' },
      { romName: 'sa', japName: 'サ' },
      { romName: 'shi', japName: 'シ' },
      { romName: 'su', japName: 'ス' },
      { romName: 'se', japName: 'セ' },
      { romName: 'so', japName: 'ソ' },
      { romName: 'ta', japName: 'タ' },
      { romName: 'chi', japName: 'チ' },
      { romName: 'tsu', japName: 'ツ' },
      { romName: 'te', japName: 'テ' },
      { romName: 'to', japName: 'ト' },
      { romName: 'na', japName: 'ナ' },
      { romName: 'ni', japName: 'ニ' },
      { romName: 'nu', japName: 'ヌ' },
      { romName: 'ne', japName: 'ネ' },
      { romName: 'no', japName: 'ノ' },
      { romName: 'ha', japName: 'ハ' },
      { romName: 'hi', japName: 'ヒ' },
      { romName: 'fu', japName: 'フ' },
      { romName: 'he', japName: 'ヘ' },
      { romName: 'ho', japName: 'ホ' },
      { romName: 'ma', japName: 'マ' },
      { romName: 'mi', japName: 'ミ' },
      { romName: 'mu', japName: 'ム' },
      { romName: 'me', japName: 'メ' },
      { romName: 'mo', japName: 'モ' },
      { romName: 'ya', japName: 'ヤ' },
      { romName: 'yu', japName: 'ユ' },
      { romName: 'yo', japName: 'ヨ' },
      { romName: 'ra', japName: 'ラ' },
      { romName: 'ri', japName: 'リ' },
      { romName: 'ru', japName: 'ル' },
      { romName: 're', japName: 'レ' },
      { romName: 'ro', japName: 'ロ' },
      { romName: 'wa', japName: 'ワ' },
      { romName: 'wi', japName: 'ヰ' },
      { romName: 'we', japName: 'ヱ' },
      { romName: 'wo', japName: 'ヲ' },
      { romName: 'n', japName: 'ン' },
    ],
  },
];

export default models;
