const models = [
  {
    name: 'katakana',
    label: [
      { romName: 'a', japName: 'ア' },
      { romName: 'i', japName: 'イ' },
      { romName: 'u', japName: 'ウ' },
      { romName: 'e', japName: 'エ' },
      { romName: 'o', japName: 'オ' },
      { romName: 'ka', japName: 'カ' },
      { romName: 'ki', japName: 'キ' },
      { romName: 'ku', japName: 'ク' },
      { romName: 'ke', japName: 'ケ' },
      { romName: 'ko', japName: 'コ' },
      { romName: 'sa', japName: 'サ' },
      { romName: 'si', japName: 'シ' },
      { romName: 'su', japName: 'ス' },
      { romName: 'se', japName: 'セ' },
      { romName: 'so', japName: 'ソ' },
      { romName: 'ta', japName: 'タ' },
      { romName: 'ti', japName: 'チ' },
      { romName: 'tu', japName: 'ツ' },
      { romName: 'te', japName: 'テ' },
      { romName: 'to', japName: 'ト' },
      { romName: 'na', japName: 'ナ' },
      { romName: 'ni', japName: 'ニ' },
      { romName: 'nu', japName: 'ヌ' },
      { romName: 'ne', japName: 'ネ' },
      { romName: 'no', japName: 'ノ' },
      { romName: 'ha', japName: 'ハ' },
      { romName: 'hi', japName: 'ヒ' },
      { romName: 'hu', japName: 'フ' },
      { romName: 'he', japName: 'ヘ' },
      { romName: 'ho', japName: 'ホ' },
      { romName: 'ma', japName: 'マ' },
      { romName: 'mi', japName: 'ミ' },
      { romName: 'mu', japName: 'ム' },
      { romName: 'me', japName: 'メ' },
      { romName: 'mo', japName: 'モ' },
      { romName: 'ya', japName: 'ヤ' },
      { romName: 'yu', japName: 'ユ' },
      { romName: 'yo', japName: 'ヨ' },
      { romName: 'ra', japName: 'ラ' },
      { romName: 'ri', japName: 'リ' },
      { romName: 'ru', japName: 'ル' },
      { romName: 're', japName: 'レ' },
      { romName: 'ro', japName: 'ロ' },
      { romName: 'wa', japName: 'ワ' },
      { romName: 'wi', japName: 'ヰ' },
      { romName: 'we', japName: 'ヱ' },
      { romName: 'wo', japName: 'ヲ' },
      { romName: 'n', japName: 'ン' },
    ],
  },
];

export default models;
